# SPDX-License-Identifier: MPL-2.0
name = "ContrastFamilies"
uuid = "10e923c4-f9ab-4da5-a18f-8d9875514f27"
authors = ["Jonathan D.A. Jewell <6759885+hyperpolymath@users.noreply.github.com>"]
version = "0.1.0-DEV"

[deps]
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
SHA = "0.7, 1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
